#!/bin/bash
service nova-api restart
sleep 1
service nova-conductor restart
sleep 1
service nova-network restart
sleep 1
service nova-consoleauth restart
sleep 1
service nova-scheduler restart
sleep 1
service nova-novncproxy restart
sleep 1

nova-manage service list
