#ifndef _LINUX_CONFIGS_H_
#define _LINUX_CONFIGS_H_

#define CONFIG_X86_32
#define CONFIG_X86
#define CONFIG_INSTRUCTION_DECODER
#define CONFIG_GENERIC_CMOS_UPDATE
#define CONFIG_CLOCKSOURCE_WATCHDOG
#define CONFIG_GENERIC_CLOCKEVENTS
#define CONFIG_GENERIC_CLOCKEVENTS_BROADCAST
#define CONFIG_LOCKDEP_SUPPORT
#define CONFIG_STACKTRACE_SUPPORT
#define CONFIG_HAVE_LATENCYTOP_SUPPORT
#define CONFIG_MMU
#define CONFIG_ZONE_DMA
#define CONFIG_NEED_DMA_MAP_STATE
#define CONFIG_NEED_SG_DMA_LENGTH
#define CONFIG_GENERIC_ISA_DMA
#define CONFIG_GENERIC_IOMAP
#define CONFIG_GENERIC_BUG
#define CONFIG_GENERIC_HWEIGHT
#define CONFIG_GENERIC_GPIO
#define CONFIG_ARCH_MAY_HAVE_PC_FDC
#define CONFIG_RWSEM_XCHGADD_ALGORITHM
#define CONFIG_ARCH_HAS_CPU_IDLE_WAIT
#define CONFIG_GENERIC_CALIBRATE_DELAY
#define CONFIG_ARCH_HAS_CPU_RELAX
#define CONFIG_ARCH_HAS_DEFAULT_IDLE
#define CONFIG_ARCH_HAS_CACHE_LINE_SIZE
#define CONFIG_HAVE_SETUP_PER_CPU_AREA
#define CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK
#define CONFIG_NEED_PER_CPU_PAGE_FIRST_CHUNK
#define CONFIG_ARCH_HIBERNATION_POSSIBLE
#define CONFIG_ARCH_SUSPEND_POSSIBLE
#define CONFIG_ARCH_POPULATES_NODE_MAP
#define CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING
#define CONFIG_ARCH_SUPPORTS_DEBUG_PAGEALLOC
#define CONFIG_HAVE_INTEL_TXT
#define CONFIG_X86_32_SMP
#define CONFIG_X86_HT
#define CONFIG_KTIME_SCALAR
#define CONFIG_ARCH_CPU_PROBE_RELEASE
#define CONFIG_HAVE_IRQ_WORK
#define CONFIG_IRQ_WORK

#define CONFIG_EXPERIMENTAL
#define CONFIG_INIT_PASS_ALL_PARAMS
#define CONFIG_HAVE_KERNEL_GZIP
#define CONFIG_HAVE_KERNEL_BZIP2
#define CONFIG_HAVE_KERNEL_LZMA
#define CONFIG_HAVE_KERNEL_XZ
#define CONFIG_HAVE_KERNEL_LZO
#define CONFIG_KERNEL_GZIP
#define CONFIG_SWAP
#define CONFIG_SYSVIPC
#define CONFIG_SYSVIPC_SYSCTL
#define CONFIG_POSIX_MQUEUE
#define CONFIG_POSIX_MQUEUE_SYSCTL
#define CONFIG_BSD_PROCESS_ACCT
#define CONFIG_BSD_PROCESS_ACCT_V3
#define CONFIG_FHANDLE
#define CONFIG_TASKSTATS
#define CONFIG_TASK_DELAY_ACCT
#define CONFIG_TASK_XACCT
#define CONFIG_TASK_IO_ACCOUNTING
#define CONFIG_AUDIT
#define CONFIG_AUDITSYSCALL
#define CONFIG_AUDIT_WATCH
#define CONFIG_AUDIT_TREE
#define CONFIG_HAVE_GENERIC_HARDIRQS

#define CONFIG_GENERIC_HARDIRQS
#define CONFIG_HAVE_SPARSE_IRQ
#define CONFIG_GENERIC_IRQ_PROBE
#define CONFIG_GENERIC_IRQ_SHOW
#define CONFIG_GENERIC_PENDING_IRQ
#define CONFIG_GENERIC_IRQ_CHIP
#define CONFIG_IRQ_FORCED_THREADING
#define CONFIG_SPARSE_IRQ

#define CONFIG_TREE_RCU
#define CONFIG_RCU_FAST_NO_HZ
#define CONFIG_HAVE_UNSTABLE_SCHED_CLOCK
#define CONFIG_CGROUPS
#define CONFIG_CGROUP_FREEZER
#define CONFIG_CGROUP_DEVICE
#define CONFIG_CPUSETS
#define CONFIG_PROC_PID_CPUSET
#define CONFIG_CGROUP_CPUACCT
#define CONFIG_RESOURCE_COUNTERS
#define CONFIG_CGROUP_MEM_RES_CTLR
#define CONFIG_CGROUP_MEM_RES_CTLR_SWAP
#define CONFIG_CGROUP_MEM_RES_CTLR_SWAP_ENABLED
#define CONFIG_CGROUP_PERF
#define CONFIG_CGROUP_SCHED
#define CONFIG_FAIR_GROUP_SCHED
#define CONFIG_CFS_BANDWIDTH
#define CONFIG_RT_GROUP_SCHED
#define CONFIG_BLK_CGROUP
#define CONFIG_NAMESPACES
#define CONFIG_UTS_NS
#define CONFIG_IPC_NS
#define CONFIG_USER_NS
#define CONFIG_PID_NS
#define CONFIG_NET_NS
#define CONFIG_SCHED_AUTOGROUP
#define CONFIG_MM_OWNER
#define CONFIG_RELAY
#define CONFIG_BLK_DEV_INITRD
#define CONFIG_RD_GZIP
#define CONFIG_RD_BZIP2
#define CONFIG_RD_LZMA
#define CONFIG_RD_XZ
#define CONFIG_RD_LZO
#define CONFIG_SYSCTL
#define CONFIG_ANON_INODES
#define CONFIG_EXPERT
#define CONFIG_UID16
#define CONFIG_SYSCTL_SYSCALL
#define CONFIG_KALLSYMS
#define CONFIG_KALLSYMS_ALL
#define CONFIG_HOTPLUG
#define CONFIG_PRINTK
#define CONFIG_BUG
#define CONFIG_ELF_CORE
#define CONFIG_PCSPKR_PLATFORM
#define CONFIG_HAVE_PCSPKR_PLATFORM
#define CONFIG_BASE_FULL
#define CONFIG_FUTEX
#define CONFIG_EPOLL
#define CONFIG_SIGNALFD
#define CONFIG_TIMERFD
#define CONFIG_EVENTFD
#define CONFIG_SHMEM
#define CONFIG_AIO
#define CONFIG_HAVE_PERF_EVENTS

#define CONFIG_PERF_EVENTS
#define CONFIG_PERF_COUNTERS
#define CONFIG_VM_EVENT_COUNTERS
#define CONFIG_PCI_QUIRKS
#define CONFIG_SLUB_DEBUG
#define CONFIG_SLUB
#define CONFIG_PROFILING
#define CONFIG_TRACEPOINTS
#define CONFIG_HAVE_OPROFILE
#define CONFIG_KPROBES
#define CONFIG_JUMP_LABEL
#define CONFIG_OPTPROBES
#define CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS
#define CONFIG_KRETPROBES
#define CONFIG_USER_RETURN_NOTIFIER
#define CONFIG_HAVE_IOREMAP_PROT
#define CONFIG_HAVE_KPROBES
#define CONFIG_HAVE_KRETPROBES
#define CONFIG_HAVE_OPTPROBES
#define CONFIG_HAVE_ARCH_TRACEHOOK
#define CONFIG_HAVE_DMA_ATTRS
#define CONFIG_USE_GENERIC_SMP_HELPERS
#define CONFIG_HAVE_REGS_AND_STACK_ACCESS_API
#define CONFIG_HAVE_DMA_API_DEBUG
#define CONFIG_HAVE_HW_BREAKPOINT
#define CONFIG_HAVE_MIXED_BREAKPOINTS_REGS
#define CONFIG_HAVE_USER_RETURN_NOTIFIER
#define CONFIG_HAVE_PERF_EVENTS_NMI
#define CONFIG_HAVE_ARCH_JUMP_LABEL
#define CONFIG_ARCH_HAVE_NMI_SAFE_CMPXCHG
#define CONFIG_HAVE_ARCH_SECCOMP_FILTER
#define CONFIG_SECCOMP_FILTER

#define CONFIG_HAVE_GENERIC_DMA_COHERENT
#define CONFIG_SLABINFO
#define CONFIG_RT_MUTEXES
#define CONFIG_MODULES
#define CONFIG_MODULE_UNLOAD
#define CONFIG_MODVERSIONS
#define CONFIG_MODULE_SRCVERSION_ALL
#define CONFIG_STOP_MACHINE
#define CONFIG_BLOCK
#define CONFIG_LBDAF
#define CONFIG_BLK_DEV_BSG
#define CONFIG_BLK_DEV_BSGLIB
#define CONFIG_BLK_DEV_INTEGRITY
#define CONFIG_BLK_DEV_THROTTLING

#define CONFIG_IOSCHED_NOOP
#define CONFIG_IOSCHED_DEADLINE
#define CONFIG_IOSCHED_CFQ
#define CONFIG_CFQ_GROUP_IOSCHED
#define CONFIG_DEFAULT_CFQ
#define CONFIG_PREEMPT_NOTIFIERS
#define CONFIG_PADATA
#define CONFIG_INLINE_SPIN_UNLOCK
#define CONFIG_INLINE_SPIN_UNLOCK_IRQ
#define CONFIG_INLINE_READ_UNLOCK
#define CONFIG_INLINE_READ_UNLOCK_IRQ
#define CONFIG_INLINE_WRITE_UNLOCK
#define CONFIG_INLINE_WRITE_UNLOCK_IRQ
#define CONFIG_MUTEX_SPIN_ON_OWNER
#define CONFIG_FREEZER

#define CONFIG_TICK_ONESHOT
#define CONFIG_NO_HZ
#define CONFIG_HIGH_RES_TIMERS
#define CONFIG_GENERIC_CLOCKEVENTS_BUILD
#define CONFIG_GENERIC_CLOCKEVENTS_MIN_ADJUST
#define CONFIG_SMP
#define CONFIG_X86_MPPARSE
#define CONFIG_X86_EXTENDED_PLATFORM
#define CONFIG_X86_WANT_INTEL_MID
#define CONFIG_X86_SUPPORTS_MEMORY_FAILURE
#define CONFIG_SCHED_OMIT_FRAME_POINTER
#define CONFIG_PARAVIRT_GUEST
#define CONFIG_XEN
#define CONFIG_XEN_DOM0
#define CONFIG_XEN_PRIVILEGED_GUEST
#define CONFIG_XEN_PVHVM
#define CONFIG_XEN_SAVE_RESTORE
#define CONFIG_KVM_CLOCK
#define CONFIG_KVM_GUEST
#define CONFIG_PARAVIRT
#define CONFIG_PARAVIRT_SPINLOCKS
#define CONFIG_PARAVIRT_CLOCK
#define CONFIG_NO_BOOTMEM
#define CONFIG_M686
#define CONFIG_X86_GENERIC
#define CONFIG_X86_CMPXCHG
#define CONFIG_CMPXCHG_LOCAL
#define CONFIG_CMPXCHG_DOUBLE
#define CONFIG_X86_XADD
#define CONFIG_X86_PPRO_FENCE
#define CONFIG_X86_WP_WORKS_OK
#define CONFIG_X86_INVLPG
#define CONFIG_X86_BSWAP
#define CONFIG_X86_POPAD_OK
#define CONFIG_X86_INTEL_USERCOPY
#define CONFIG_X86_USE_PPRO_CHECKSUM
#define CONFIG_X86_TSC
#define CONFIG_X86_CMPXCHG64
#define CONFIG_X86_CMOV
#define CONFIG_X86_DEBUGCTLMSR
#define CONFIG_PROCESSOR_SELECT
#define CONFIG_CPU_SUP_INTEL
#define CONFIG_CPU_SUP_CYRIX_32
#define CONFIG_CPU_SUP_AMD
#define CONFIG_CPU_SUP_CENTAUR
#define CONFIG_CPU_SUP_TRANSMETA_32
#define CONFIG_CPU_SUP_UMC_32
#define CONFIG_HPET_TIMER
#define CONFIG_HPET_EMULATE_RTC
#define CONFIG_DMI
#define CONFIG_SWIOTLB
#define CONFIG_IOMMU_HELPER
#define CONFIG_SCHED_SMT
#define CONFIG_SCHED_MC
#define CONFIG_PREEMPT_VOLUNTARY
#define CONFIG_X86_LOCAL_APIC
#define CONFIG_X86_IO_APIC
#define CONFIG_X86_REROUTE_FOR_BROKEN_BOOT_IRQS
#define CONFIG_X86_MCE
#define CONFIG_X86_MCE_INTEL
#define CONFIG_X86_MCE_AMD
#define CONFIG_X86_MCE_THRESHOLD
#define CONFIG_X86_THERMAL_VECTOR
#define CONFIG_VM86
#define CONFIG_X86_REBOOTFIXUPS
#define CONFIG_MICROCODE_INTEL
#define CONFIG_MICROCODE_AMD
#define CONFIG_MICROCODE_OLD_INTERFACE
#define CONFIG_HIGHMEM64G
#define CONFIG_VMSPLIT_3G
#define CONFIG_HIGHMEM
#define CONFIG_X86_PAE
#define CONFIG_ARCH_PHYS_ADDR_T_64BIT
#define CONFIG_ARCH_DMA_ADDR_T_64BIT
#define CONFIG_ARCH_FLATMEM_ENABLE
#define CONFIG_ARCH_SPARSEMEM_ENABLE
#define CONFIG_ARCH_SELECT_MEMORY_MODEL
#define CONFIG_SELECT_MEMORY_MODEL
#define CONFIG_FLATMEM_MANUAL
#define CONFIG_FLATMEM
#define CONFIG_FLAT_NODE_MEM_MAP
#define CONFIG_SPARSEMEM_STATIC
#define CONFIG_HAVE_MEMBLOCK
#define CONFIG_PAGEFLAGS_EXTENDED
#define CONFIG_COMPACTION
#define CONFIG_MIGRATION
#define CONFIG_PHYS_ADDR_T_64BIT
#define CONFIG_BOUNCE
#define CONFIG_VIRT_TO_BUS
#define CONFIG_MMU_NOTIFIER
#define CONFIG_KSM
#define CONFIG_ARCH_SUPPORTS_MEMORY_FAILURE
#define CONFIG_MEMORY_FAILURE
#define CONFIG_TRANSPARENT_HUGEPAGE
#define CONFIG_TRANSPARENT_HUGEPAGE_MADVISE
#define CONFIG_CLEANCACHE
#define CONFIG_HIGHPTE
#define CONFIG_X86_CHECK_BIOS_CORRUPTION
#define CONFIG_X86_BOOTPARAM_MEMORY_CORRUPTION_CHECK
#define CONFIG_MTRR
#define CONFIG_MTRR_SANITIZER
#define CONFIG_X86_PAT
#define CONFIG_ARCH_USES_PG_UNCACHED
#define CONFIG_ARCH_RANDOM
#define CONFIG_EFI
#define CONFIG_SECCOMP
#define CONFIG_CC_STACKPROTECTOR
#define CONFIG_HZ_250
#define CONFIG_SCHED_HRTICK
#define CONFIG_KEXEC
#define CONFIG_CRASH_DUMP
#define CONFIG_KEXEC_JUMP
#define CONFIG_RELOCATABLE
#define CONFIG_X86_NEED_RELOCS
#define CONFIG_HOTPLUG_CPU
#define CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG

#define CONFIG_SUSPEND
#define CONFIG_SUSPEND_FREEZER
#define CONFIG_HIBERNATE_CALLBACKS
#define CONFIG_HIBERNATION
#define CONFIG_PM_SLEEP
#define CONFIG_PM_SLEEP_SMP
#define CONFIG_PM_RUNTIME
#define CONFIG_PM
#define CONFIG_PM_DEBUG
#define CONFIG_PM_ADVANCED_DEBUG
#define CONFIG_PM_TEST_SUSPEND
#define CONFIG_CAN_PM_TRACE
#define CONFIG_PM_TRACE
#define CONFIG_PM_TRACE_RTC
#define CONFIG_ACPI
#define CONFIG_ACPI_SLEEP
#define CONFIG_ACPI_PROCFS_POWER
#define CONFIG_ACPI_PROC_EVENT
#define CONFIG_ACPI_AC
#define CONFIG_ACPI_BATTERY
#define CONFIG_ACPI_BUTTON
#define CONFIG_ACPI_FAN
#define CONFIG_ACPI_DOCK
#define CONFIG_ACPI_PROCESSOR
#define CONFIG_ACPI_HOTPLUG_CPU
#define CONFIG_ACPI_THERMAL
#define CONFIG_X86_PM_TIMER
#define CONFIG_ACPI_CONTAINER
#define CONFIG_ACPI_HED
#define CONFIG_ACPI_APEI
#define CONFIG_ACPI_APEI_GHES
#define CONFIG_ACPI_APEI_PCIEAER
#define CONFIG_ACPI_APEI_MEMORY_FAILURE
#define CONFIG_SFI
#define CONFIG_X86_APM_BOOT

#define CONFIG_CPU_FREQ
#define CONFIG_CPU_FREQ_TABLE
#define CONFIG_CPU_FREQ_STAT
#define CONFIG_CPU_FREQ_STAT_DETAILS
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE
#define CONFIG_CPU_FREQ_GOV_POWERSAVE
#define CONFIG_CPU_FREQ_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_ONDEMAND
#define CONFIG_CPU_FREQ_GOV_CONSERVATIVE

#define CONFIG_X86_ACPI_CPUFREQ
#define CONFIG_X86_POWERNOW_K6
#define CONFIG_X86_POWERNOW_K7
#define CONFIG_X86_POWERNOW_K7_ACPI
#define CONFIG_X86_POWERNOW_K8
#define CONFIG_X86_GX_SUSPMOD
#define CONFIG_X86_SPEEDSTEP_CENTRINO
#define CONFIG_X86_SPEEDSTEP_CENTRINO_TABLE
#define CONFIG_X86_SPEEDSTEP_ICH
#define CONFIG_X86_SPEEDSTEP_SMI
#define CONFIG_X86_CPUFREQ_NFORCE2
#define CONFIG_X86_LONGRUN
#define CONFIG_X86_LONGHAUL

#define CONFIG_X86_SPEEDSTEP_LIB
#define CONFIG_X86_SPEEDSTEP_RELAXED_CAP_CHECK
#define CONFIG_CPU_IDLE
#define CONFIG_CPU_IDLE_GOV_LADDER
#define CONFIG_CPU_IDLE_GOV_MENU

#define CONFIG_PCI
#define CONFIG_PCI_GOANY
#define CONFIG_PCI_BIOS
#define CONFIG_PCI_DIRECT
#define CONFIG_PCI_MMCONFIG
#define CONFIG_PCI_XEN
#define CONFIG_PCI_DOMAINS
#define CONFIG_PCIEPORTBUS
#define CONFIG_HOTPLUG_PCI_PCIE
#define CONFIG_PCIEAER
#define CONFIG_PCIEASPM
#define CONFIG_PCIE_PME
#define CONFIG_ARCH_SUPPORTS_MSI
#define CONFIG_PCI_MSI
#define CONFIG_HT_IRQ
#define CONFIG_PCI_ATS
#define CONFIG_PCI_IOV
#define CONFIG_PCI_PRI
#define CONFIG_PCI_PASID
#define CONFIG_PCI_IOAPIC
#define CONFIG_PCI_LABEL
#define CONFIG_ISA_DMA_API
#define CONFIG_ISA
#define CONFIG_EISA
#define CONFIG_EISA_VLB_PRIMING
#define CONFIG_EISA_PCI_EISA
#define CONFIG_EISA_VIRTUAL_ROOT
#define CONFIG_EISA_NAMES
#define CONFIG_MCA
#define CONFIG_MCA_LEGACY
#define CONFIG_ALIX
#define CONFIG_AMD_NB
#define CONFIG_PCMCIA_LOAD_CIS
#define CONFIG_CARDBUS

#define CONFIG_YENTA_O2
#define CONFIG_YENTA_RICOH
#define CONFIG_YENTA_TI
#define CONFIG_YENTA_ENE_TUNE
#define CONFIG_YENTA_TOSHIBA
#define CONFIG_PCMCIA_PROBE
#define CONFIG_PCCARD_NONSTATIC
#define CONFIG_HOTPLUG_PCI
#define CONFIG_HOTPLUG_PCI_COMPAQ_NVRAM
#define CONFIG_HOTPLUG_PCI_CPCI
#define CONFIG_RAPIDIO
#define CONFIG_RAPIDIO_TSI721
#define CONFIG_RAPIDIO_TSI57X
#define CONFIG_RAPIDIO_CPS_XX
#define CONFIG_RAPIDIO_TSI568
#define CONFIG_RAPIDIO_CPS_GEN2
#define CONFIG_RAPIDIO_TSI500

#define CONFIG_BINFMT_ELF
#define CONFIG_HAVE_AOUT
#define CONFIG_HAVE_ATOMIC_IOMAP
#define CONFIG_HAVE_TEXT_POKE_SMP
#define CONFIG_NET

#define CONFIG_PACKET
#define CONFIG_UNIX
#define CONFIG_XFRM
#define CONFIG_INET
#define CONFIG_IP_MULTICAST
#define CONFIG_IP_ADVANCED_ROUTER
#define CONFIG_IP_FIB_TRIE_STATS
#define CONFIG_IP_MULTIPLE_TABLES
#define CONFIG_IP_ROUTE_MULTIPATH
#define CONFIG_IP_ROUTE_VERBOSE
#define CONFIG_IP_ROUTE_CLASSID
#define CONFIG_NET_IPGRE_BROADCAST
#define CONFIG_IP_MROUTE
#define CONFIG_IP_PIMSM_V1
#define CONFIG_IP_PIMSM_V2
#define CONFIG_SYN_COOKIES
#define CONFIG_INET_LRO
#define CONFIG_TCP_CONG_ADVANCED
#define CONFIG_TCP_CONG_CUBIC
#define CONFIG_DEFAULT_CUBIC
#define CONFIG_TCP_MD5SIG
#define CONFIG_IPV6
#define CONFIG_IPV6_PRIVACY
#define CONFIG_IPV6_ROUTER_PREF
#define CONFIG_IPV6_ROUTE_INFO
#define CONFIG_IPV6_SIT_6RD
#define CONFIG_IPV6_NDISC_NODETYPE
#define CONFIG_IPV6_MULTIPLE_TABLES
#define CONFIG_IPV6_SUBTREES
#define CONFIG_IPV6_MROUTE
#define CONFIG_IPV6_MROUTE_MULTIPLE_TABLES
#define CONFIG_IPV6_PIMSM_V2
#define CONFIG_NETLABEL
#define CONFIG_NETWORK_SECMARK
#define CONFIG_NETFILTER
#define CONFIG_NETFILTER_ADVANCED
#define CONFIG_BRIDGE_NETFILTER

#define CONFIG_NF_CONNTRACK_MARK
#define CONFIG_NF_CONNTRACK_SECMARK
#define CONFIG_NF_CONNTRACK_ZONES
#define CONFIG_NF_CONNTRACK_EVENTS
#define CONFIG_NF_CONNTRACK_TIMESTAMP



#define CONFIG_IP_VS_IPV6

#define CONFIG_IP_VS_PROTO_TCP
#define CONFIG_IP_VS_PROTO_UDP
#define CONFIG_IP_VS_PROTO_AH_ESP
#define CONFIG_IP_VS_PROTO_ESP
#define CONFIG_IP_VS_PROTO_AH
#define CONFIG_IP_VS_PROTO_SCTP


#define CONFIG_IP_VS_NFCT

#define CONFIG_NF_CONNTRACK_PROC_COMPAT
#define CONFIG_NF_NAT_NEEDED



#define CONFIG_IP_DCCP_CCID3
#define CONFIG_IP_DCCP_TFRC_LIB

#define CONFIG_SCTP_HMAC_MD5
#define CONFIG_BRIDGE_IGMP_SNOOPING
#define CONFIG_NET_DSA_TAG_DSA
#define CONFIG_NET_DSA_TAG_EDSA
#define CONFIG_NET_DSA_TAG_TRAILER
#define CONFIG_VLAN_8021Q_GVRP
#define CONFIG_LLC
#define CONFIG_COPS_DAYNA
#define CONFIG_COPS_TANGENT
#define CONFIG_IPDDP_ENCAP
#define CONFIG_IPDDP_DECAP
#define CONFIG_ECONET_AUNUDP
#define CONFIG_ECONET_NATIVE
#define CONFIG_NET_SCHED


#define CONFIG_NET_CLS
#define CONFIG_CLS_U32_MARK
#define CONFIG_NET_EMATCH
#define CONFIG_NET_CLS_ACT
#define CONFIG_GACT_PROB
#define CONFIG_NET_SCH_FIFO
#define CONFIG_DCB
#define CONFIG_DNS_RESOLVER
#define CONFIG_RPS
#define CONFIG_RFS_ACCEL
#define CONFIG_XPS

#define CONFIG_HAMRADIO

#define CONFIG_AX25_DAMA_SLAVE


#define CONFIG_CAN_CALC_BITTIMING


#define CONFIG_IRDA_ULTRA

#define CONFIG_IRDA_CACHE_LAST_LSAP
#define CONFIG_IRDA_FAST_RR
#define CONFIG_IRDA_DEBUG



#define CONFIG_DONGLE

#define CONFIG_BT_L2CAP
#define CONFIG_BT_SCO
#define CONFIG_BT_RFCOMM_TTY
#define CONFIG_BT_BNEP_MC_FILTER
#define CONFIG_BT_BNEP_PROTO_FILTER

#define CONFIG_BT_HCIUART_H4
#define CONFIG_BT_HCIUART_BCSP
#define CONFIG_BT_HCIUART_ATH3K
#define CONFIG_BT_HCIUART_LL
#define CONFIG_FIB_RULES
#define CONFIG_WIRELESS
#define CONFIG_WIRELESS_EXT
#define CONFIG_WEXT_CORE
#define CONFIG_WEXT_PROC
#define CONFIG_WEXT_SPY
#define CONFIG_WEXT_PRIV
#define CONFIG_NL80211_TESTMODE
#define CONFIG_CFG80211_REG_DEBUG
#define CONFIG_CFG80211_DEFAULT_PS
#define CONFIG_CFG80211_DEBUGFS
#define CONFIG_CFG80211_WEXT
#define CONFIG_WIRELESS_EXT_SYSFS
#define CONFIG_MAC80211_HAS_RC
#define CONFIG_MAC80211_RC_PID
#define CONFIG_MAC80211_RC_MINSTREL
#define CONFIG_MAC80211_RC_MINSTREL_HT
#define CONFIG_MAC80211_RC_DEFAULT_MINSTREL
#define CONFIG_MAC80211_MESH
#define CONFIG_MAC80211_LEDS
#define CONFIG_MAC80211_DEBUGFS
#define CONFIG_MAC80211_DEBUG_MENU
#define CONFIG_MAC80211_DRIVER_API_TRACER
#define CONFIG_RFKILL
#define CONFIG_RFKILL_LEDS
#define CONFIG_RFKILL_INPUT
#define CONFIG_CEPH_LIB_USE_DNS_RESOLVER



#define CONFIG_DEVTMPFS
#define CONFIG_DEVTMPFS_MOUNT
#define CONFIG_PREVENT_FIRMWARE_BUILD
#define CONFIG_FW_LOADER
#define CONFIG_FIRMWARE_IN_KERNEL
#define CONFIG_SYS_HYPERVISOR
#define CONFIG_REGMAP
#define CONFIG_REGMAP_I2C
#define CONFIG_REGMAP_SPI
#define CONFIG_CONNECTOR
#define CONFIG_PROC_EVENTS

#define CONFIG_HAVE_MTD_OTP
#define CONFIG_NFTL_RW

#define CONFIG_MTD_MAP_BANK_WIDTH_1
#define CONFIG_MTD_MAP_BANK_WIDTH_2
#define CONFIG_MTD_MAP_BANK_WIDTH_4
#define CONFIG_MTD_CFI_I1
#define CONFIG_MTD_CFI_I2

#define CONFIG_MTD_COMPLEX_MAPPINGS

#define CONFIG_MTD_DATAFLASH_OTP
#define CONFIG_M25PXX_USE_FAST_READ

#define CONFIG_MTD_NAND_ECC_BCH
#define CONFIG_MTD_ONENAND_VERIFY_WRITE
#define CONFIG_MTD_ONENAND_2X_PROGRAM

#define CONFIG_PARPORT_PC_FIFO
#define CONFIG_PARPORT_1284
#define CONFIG_PARPORT_NOT_PC
#define CONFIG_PNP
#define CONFIG_PNP_DEBUG_MESSAGES

#define CONFIG_ISAPNP
#define CONFIG_PNPBIOS
#define CONFIG_PNPBIOS_PROC_FS
#define CONFIG_PNPACPI
#define CONFIG_BLK_DEV


#define CONFIG_CISS_SCSI_TAPE
#define CONFIG_BLK_DEV_LOOP
#define CONFIG_BLK_DEV_RAM
#define CONFIG_XEN_BLKDEV_FRONTEND
#define CONFIG_VIRTIO_BLK
#define CONFIG_MISC_DEVICES

#define CONFIG_CB710_DEBUG_ASSUMPTIONS
#define CONFIG_IWMC3200TOP_DEBUGFS


#define CONFIG_HAVE_IDE

#define CONFIG_SCSI_MOD
#define CONFIG_SCSI
#define CONFIG_SCSI_DMA
#define CONFIG_SCSI_NETLINK
#define CONFIG_SCSI_PROC_FS

#define CONFIG_BLK_DEV_SD
#define CONFIG_BLK_DEV_SR
#define CONFIG_CHR_DEV_SG
#define CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS
#define CONFIG_SCSI_LOGGING
#define CONFIG_SCSI_SCAN_ASYNC

#define CONFIG_SCSI_SPI_ATTRS
#define CONFIG_SCSI_FC_TGT_ATTRS
#define CONFIG_SCSI_SAS_ATA
#define CONFIG_SCSI_SAS_HOST_SMP
#define CONFIG_SCSI_SRP_TGT_ATTRS
#define CONFIG_SCSI_LOWLEVEL
#define CONFIG_AIC7XXX_DEBUG_ENABLE
#define CONFIG_AIC7XXX_REG_PRETTY_PRINT
#define CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_REG_PRETTY_PRINT
#define CONFIG_SCSI_MVSAS_DEBUG
#define CONFIG_MEGARAID_NEWGEN
#define CONFIG_SCSI_EATA_TAGGED_QUEUE
#define CONFIG_SCSI_EATA_LINKED_COMMANDS
#define CONFIG_SCSI_GENERIC_NCR53C400
#define CONFIG_IBMMCA_SCSI_ORDER_STANDARD
#define CONFIG_SCSI_SYM53C8XX_2
#define CONFIG_SCSI_SYM53C8XX_MMIO
#define CONFIG_SCSI_U14_34F_TAGGED_QUEUE
#define CONFIG_SCSI_U14_34F_LINKED_COMMANDS
#define CONFIG_SCSI_LOWLEVEL_PCMCIA
#define CONFIG_SCSI_DH
#define CONFIG_ATA
#define CONFIG_ATA_VERBOSE_ERROR
#define CONFIG_ATA_ACPI
#define CONFIG_SATA_PMP

#define CONFIG_SATA_AHCI
#define CONFIG_ATA_SFF

#define CONFIG_PDC_ADMA
#define CONFIG_ATA_BMDMA

#define CONFIG_ATA_PIIX

#define CONFIG_PATA_SIS


#define CONFIG_PATA_ACPI
#define CONFIG_ATA_GENERIC
#define CONFIG_MD
#define CONFIG_BLK_DEV_MD
#define CONFIG_MD_AUTODETECT
#define CONFIG_BLK_DEV_DM
#define CONFIG_DM_UEVENT
#define CONFIG_FUSION
#define CONFIG_FUSION_LOGGING

#define CONFIG_FIREWIRE_OHCI_DEBUG
#define CONFIG_I2O_LCT_NOTIFY_ON_CHANGES
#define CONFIG_I2O_EXT_ADAPTEC
#define CONFIG_I2O_EXT_ADAPTEC_DMA64
#define CONFIG_I2O_CONFIG_OLD_IOCTL
#define CONFIG_MACINTOSH_DRIVERS
#define CONFIG_NETDEVICES
#define CONFIG_NET_CORE
#define CONFIG_NET_FC
#define CONFIG_MII
#define CONFIG_NETCONSOLE_DYNAMIC
#define CONFIG_NETPOLL
#define CONFIG_NET_POLL_CONTROLLER
#define CONFIG_TUN
#define CONFIG_VIRTIO_NET
#define CONFIG_ATM_DRIVERS
#define CONFIG_ATM_IDT77252_USE_SUNI
#define CONFIG_ATM_HE_USE_SUNI


#define CONFIG_NET_DSA_MV88E6XXX_NEED_PPU
#define CONFIG_ETHERNET
#define CONFIG_NET_VENDOR_3COM
#define CONFIG_NET_VENDOR_ADAPTEC
#define CONFIG_NET_VENDOR_ALTEON
#define CONFIG_NET_VENDOR_AMD
#define CONFIG_NET_VENDOR_ATHEROS
#define CONFIG_NET_VENDOR_BROADCOM
#define CONFIG_B44_PCI_AUTOSELECT
#define CONFIG_B44_PCICORE_AUTOSELECT
#define CONFIG_B44_PCI
#define CONFIG_NET_VENDOR_BROCADE
#define CONFIG_NET_VENDOR_CHELSIO
#define CONFIG_CHELSIO_T1_1G
#define CONFIG_NET_VENDOR_CIRRUS
#define CONFIG_NET_VENDOR_CISCO
#define CONFIG_NET_VENDOR_DEC
#define CONFIG_NET_TULIP
#define CONFIG_NET_VENDOR_DLINK
#define CONFIG_NET_VENDOR_EMULEX
#define CONFIG_NET_VENDOR_EXAR
#define CONFIG_NET_VENDOR_FUJITSU
#define CONFIG_NET_VENDOR_HP
#define CONFIG_NET_VENDOR_IBM
#define CONFIG_NET_VENDOR_INTEL
#define CONFIG_IGB_DCA
#define CONFIG_IXGBE_DCA
#define CONFIG_IXGBE_DCB
#define CONFIG_NET_VENDOR_I825XX
#define CONFIG_NET_VENDOR_MARVELL
#define CONFIG_SKGE_GENESIS
#define CONFIG_NET_VENDOR_MELLANOX
#define CONFIG_MLX4_DEBUG
#define CONFIG_NET_VENDOR_MICREL
#define CONFIG_NET_VENDOR_MICROCHIP
#define CONFIG_NET_VENDOR_MYRI
#define CONFIG_MYRI10GE_DCA
#define CONFIG_NET_VENDOR_NATSEMI
#define CONFIG_NET_VENDOR_8390
#define CONFIG_NET_VENDOR_NVIDIA
#define CONFIG_NET_VENDOR_OKI
#define CONFIG_NET_PACKET_ENGINE
#define CONFIG_NET_VENDOR_QLOGIC
#define CONFIG_NET_VENDOR_RACAL
#define CONFIG_NET_VENDOR_REALTEK
#define CONFIG_8139TOO_PIO
#define CONFIG_8139TOO_8129
#define CONFIG_NET_VENDOR_RDC
#define CONFIG_NET_VENDOR_SEEQ
#define CONFIG_NET_VENDOR_SILAN
#define CONFIG_NET_VENDOR_SIS
#define CONFIG_SFC_MTD
#define CONFIG_NET_VENDOR_SMSC
#define CONFIG_NET_VENDOR_STMICRO
#define CONFIG_STMMAC_RING
#define CONFIG_NET_VENDOR_SUN
#define CONFIG_NET_VENDOR_TEHUTI
#define CONFIG_NET_VENDOR_TI
#define CONFIG_NET_VENDOR_VIA
#define CONFIG_VIA_RHINE_MMIO
#define CONFIG_NET_VENDOR_XIRCOM
#define CONFIG_FDDI
#define CONFIG_PHYLIB

#define CONFIG_MARVELL_PHY
#define CONFIG_DAVICOM_PHY
#define CONFIG_QSEMI_PHY
#define CONFIG_LXT_PHY
#define CONFIG_CICADA_PHY
#define CONFIG_VITESSE_PHY
#define CONFIG_SMSC_PHY
#define CONFIG_BROADCOM_PHY
#define CONFIG_ICPLUS_PHY
#define CONFIG_REALTEK_PHY
#define CONFIG_NATIONAL_PHY
#define CONFIG_STE10XP
#define CONFIG_LSI_ET1011C_PHY
#define CONFIG_FIXED_PHY
#define CONFIG_PPP
#define CONFIG_PPP_FILTER
#define CONFIG_PPP_MULTILINK
#define CONFIG_SLHC
#define CONFIG_SLIP_COMPRESSED
#define CONFIG_SLIP_SMART
#define CONFIG_SLIP_MODE_SLIP6
#define CONFIG_TR

#define CONFIG_USB_ALI_M5632
#define CONFIG_USB_AN2720
#define CONFIG_USB_BELKIN
#define CONFIG_USB_ARMLINUX
#define CONFIG_USB_EPSON2888
#define CONFIG_USB_KC2190
#define CONFIG_WLAN
#define CONFIG_RTL8187_LEDS
#define CONFIG_ATH5K_PCI
#define CONFIG_ATH9K_PCI
#define CONFIG_ATH9K_AHB
#define CONFIG_ATH9K_DEBUGFS
#define CONFIG_ATH9K_RATE_CONTROL
#define CONFIG_ATH9K_HTC_DEBUGFS
#define CONFIG_CARL9170_LEDS
#define CONFIG_CARL9170_WPC
#define CONFIG_CARL9170_HWRNG
#define CONFIG_B43_BCMA
#define CONFIG_B43_SSB
#define CONFIG_B43_PCI_AUTOSELECT
#define CONFIG_B43_PCICORE_AUTOSELECT
#define CONFIG_B43_BCMA_PIO
#define CONFIG_B43_PIO
#define CONFIG_B43_PHY_N
#define CONFIG_B43_PHY_LP
#define CONFIG_B43_PHY_HT
#define CONFIG_B43_LEDS
#define CONFIG_B43_HWRNG
#define CONFIG_B43LEGACY_PCI_AUTOSELECT
#define CONFIG_B43LEGACY_PCICORE_AUTOSELECT
#define CONFIG_B43LEGACY_LEDS
#define CONFIG_B43LEGACY_HWRNG
#define CONFIG_B43LEGACY_DEBUG
#define CONFIG_B43LEGACY_DMA
#define CONFIG_B43LEGACY_PIO
#define CONFIG_B43LEGACY_DMA_AND_PIO_MODE
#define CONFIG_HOSTAP_FIRMWARE
#define CONFIG_HOSTAP_FIRMWARE_NVRAM
#define CONFIG_IPW2100_MONITOR
#define CONFIG_IPW2200_MONITOR
#define CONFIG_IPW2200_RADIOTAP
#define CONFIG_IPW2200_PROMISCUOUS
#define CONFIG_IPW2200_QOS
#define CONFIG_LIBIPW_DEBUG

#define CONFIG_IWLWIFI_DEBUGFS
#define CONFIG_IWLWIFI_DEVICE_TRACING

#define CONFIG_IWM_TRACING
#define CONFIG_LIBERTAS_MESH
#define CONFIG_HERMES_CACHE_FW_ON_INIT
#define CONFIG_P54_LEDS
#define CONFIG_RT2800PCI_RT33XX
#define CONFIG_RT2800PCI_RT35XX
#define CONFIG_RT2800PCI_RT53XX
#define CONFIG_RT2800USB_RT33XX
#define CONFIG_RT2800USB_RT35XX
#define CONFIG_RT2800USB_RT53XX
#define CONFIG_RT2800USB_UNKNOWN
#define CONFIG_RT2X00_LIB_FIRMWARE
#define CONFIG_RT2X00_LIB_CRYPTO
#define CONFIG_RT2X00_LIB_LEDS
#define CONFIG_WL12XX_PLATFORM_DATA

#define CONFIG_WIMAX_IWMC3200_SDIO
#define CONFIG_WAN
#define CONFIG_DSCC4_PCISYNC
#define CONFIG_DSCC4_PCI_RST
#define CONFIG_CYCLOMX_X25
#define CONFIG_XEN_NETDEV_FRONTEND
#define CONFIG_ISDN
#define CONFIG_ISDN_PPP
#define CONFIG_ISDN_PPP_VJ
#define CONFIG_ISDN_MPP
#define CONFIG_IPPP_FILTER
#define CONFIG_ISDN_AUDIO
#define CONFIG_ISDN_TTY_FAX
#define CONFIG_ISDN_X25




#define CONFIG_HISAX_EURO
#define CONFIG_DE_AOC
#define CONFIG_HISAX_1TR6
#define CONFIG_HISAX_NI1

#define CONFIG_HISAX_16_0
#define CONFIG_HISAX_16_3
#define CONFIG_HISAX_TELESPCI
#define CONFIG_HISAX_S0BOX
#define CONFIG_HISAX_AVM_A1
#define CONFIG_HISAX_FRITZPCI
#define CONFIG_HISAX_AVM_A1_PCMCIA
#define CONFIG_HISAX_ELSA
#define CONFIG_HISAX_IX1MICROR2
#define CONFIG_HISAX_DIEHLDIVA
#define CONFIG_HISAX_ASUSCOM
#define CONFIG_HISAX_TELEINT
#define CONFIG_HISAX_HFCS
#define CONFIG_HISAX_SEDLBAUER
#define CONFIG_HISAX_SPORTSTER
#define CONFIG_HISAX_MIC
#define CONFIG_HISAX_NETJET
#define CONFIG_HISAX_NETJET_U
#define CONFIG_HISAX_NICCY
#define CONFIG_HISAX_ISURF
#define CONFIG_HISAX_HSTSAPHIR
#define CONFIG_HISAX_BKM_A4T
#define CONFIG_HISAX_SCT_QUADRO
#define CONFIG_HISAX_GAZEL
#define CONFIG_HISAX_HFC_PCI
#define CONFIG_HISAX_W6692
#define CONFIG_HISAX_HFC_SX
#define CONFIG_HISAX_ENTERNOW_PCI



#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON
#define CONFIG_CAPI_TRACE
#define CONFIG_ISDN_CAPI_MIDDLEWARE

#define CONFIG_CAPI_AVM
#define CONFIG_ISDN_DRV_AVMB1_B1PCIV4
#define CONFIG_CAPI_EICON
#define CONFIG_ISDN_DIVAS_BRIPCI
#define CONFIG_ISDN_DIVAS_PRIPCI
#define CONFIG_GIGASET_I4L
#define CONFIG_HYSDN_CAPI


#define CONFIG_INPUT

#define CONFIG_INPUT_MOUSEDEV
#define CONFIG_INPUT_MOUSEDEV_PSAUX
#define CONFIG_INPUT_EVDEV

#define CONFIG_INPUT_KEYBOARD
#define CONFIG_KEYBOARD_ATKBD
#define CONFIG_INPUT_MOUSE
#define CONFIG_MOUSE_PS2_ALPS
#define CONFIG_MOUSE_PS2_LOGIPS2PP
#define CONFIG_MOUSE_PS2_SYNAPTICS
#define CONFIG_MOUSE_PS2_LIFEBOOK
#define CONFIG_MOUSE_PS2_TRACKPOINT
#define CONFIG_MOUSE_PS2_ELANTECH
#define CONFIG_MOUSE_PS2_SENTELIC
#define CONFIG_INPUT_JOYSTICK
#define CONFIG_JOYSTICK_IFORCE_USB
#define CONFIG_JOYSTICK_IFORCE_232
#define CONFIG_JOYSTICK_XPAD_FF
#define CONFIG_JOYSTICK_XPAD_LEDS
#define CONFIG_INPUT_TABLET
#define CONFIG_INPUT_TOUCHSCREEN
#define CONFIG_TOUCHSCREEN_WM9705
#define CONFIG_TOUCHSCREEN_WM9712
#define CONFIG_TOUCHSCREEN_WM9713
#define CONFIG_TOUCHSCREEN_USB_EGALAX
#define CONFIG_TOUCHSCREEN_USB_PANJIT
#define CONFIG_TOUCHSCREEN_USB_3M
#define CONFIG_TOUCHSCREEN_USB_ITM
#define CONFIG_TOUCHSCREEN_USB_ETURBO
#define CONFIG_TOUCHSCREEN_USB_GUNZE
#define CONFIG_TOUCHSCREEN_USB_DMC_TSC10
#define CONFIG_TOUCHSCREEN_USB_IRTOUCH
#define CONFIG_TOUCHSCREEN_USB_IDEALTEK
#define CONFIG_TOUCHSCREEN_USB_GENERAL_TOUCH
#define CONFIG_TOUCHSCREEN_USB_GOTOP
#define CONFIG_TOUCHSCREEN_USB_JASTEC
#define CONFIG_TOUCHSCREEN_USB_E2I
#define CONFIG_TOUCHSCREEN_USB_ZYTRONIC
#define CONFIG_TOUCHSCREEN_USB_ETT_TC45USB
#define CONFIG_TOUCHSCREEN_USB_NEXIO
#define CONFIG_INPUT_MISC
#define CONFIG_INPUT_UINPUT

#define CONFIG_SERIO
#define CONFIG_SERIO_I8042
#define CONFIG_SERIO_LIBPS2

#define CONFIG_VT
#define CONFIG_CONSOLE_TRANSLATIONS
#define CONFIG_VT_CONSOLE
#define CONFIG_VT_CONSOLE_SLEEP
#define CONFIG_HW_CONSOLE
#define CONFIG_VT_HW_CONSOLE_BINDING
#define CONFIG_UNIX98_PTYS
#define CONFIG_DEVPTS_MULTIPLE_INSTANCES
#define CONFIG_LEGACY_PTYS
#define CONFIG_SERIAL_NONSTANDARD
#define CONFIG_STALDRV

#define CONFIG_SERIAL_8250
#define CONFIG_SERIAL_8250_CONSOLE
#define CONFIG_FIX_EARLYCON_MEM
#define CONFIG_SERIAL_8250_PCI
#define CONFIG_SERIAL_8250_PNP
#define CONFIG_SERIAL_8250_EXTENDED
#define CONFIG_SERIAL_8250_MANY_PORTS
#define CONFIG_SERIAL_8250_SHARE_IRQ
#define CONFIG_SERIAL_8250_RSA

#define CONFIG_SERIAL_CORE
#define CONFIG_SERIAL_CORE_CONSOLE
#define CONFIG_CONSOLE_POLL
#define CONFIG_TTY_PRINTK
#define CONFIG_HVC_DRIVER
#define CONFIG_HVC_IRQ
#define CONFIG_HVC_XEN
#define CONFIG_HW_RANDOM

#define CONFIG_HPET
#define CONFIG_HPET_MMAP
#define CONFIG_TCG_TPM
#define CONFIG_DEVPORT
#define CONFIG_I2C
#define CONFIG_I2C_BOARDINFO
#define CONFIG_I2C_COMPAT








#define CONFIG_SPI
#define CONFIG_SPI_MASTER

#define CONFIG_SPI_PXA2XX_PCI
#define CONFIG_SPI_DESIGNWARE
#define CONFIG_SPI_DW_MID_DMA





#define CONFIG_ARCH_WANT_OPTIONAL_GPIOLIB
#define CONFIG_GPIOLIB
#define CONFIG_GPIO_SYSFS


#define CONFIG_GPIO_SX150X
#define CONFIG_GPIO_STMPE
#define CONFIG_GPIO_TC3589X

#define CONFIG_GPIO_LANGWELL
#define CONFIG_GPIO_TIMBERDALE


#define CONFIG_GPIO_UCB1400

#define CONFIG_GPIO_TPS65910
#define CONFIG_W1_CON


#define CONFIG_POWER_SUPPLY
#define CONFIG_BATTERY_BQ27X00_I2C
#define CONFIG_BATTERY_BQ27X00_PLATFORM
#define CONFIG_HWMON


#define CONFIG_THERMAL
#define CONFIG_THERMAL_HWMON
#define CONFIG_WATCHDOG
#define CONFIG_WATCHDOG_CORE

#define CONFIG_ITCO_VENDOR_SUPPORT



#define CONFIG_SSB_POSSIBLE

#define CONFIG_SSB_SPROM
#define CONFIG_SSB_BLOCKIO
#define CONFIG_SSB_PCIHOST_POSSIBLE
#define CONFIG_SSB_PCIHOST
#define CONFIG_SSB_B43_PCI_BRIDGE
#define CONFIG_SSB_PCMCIAHOST_POSSIBLE
#define CONFIG_SSB_SDIOHOST_POSSIBLE
#define CONFIG_SSB_SDIOHOST
#define CONFIG_SSB_DRIVER_PCICORE_POSSIBLE
#define CONFIG_SSB_DRIVER_PCICORE
#define CONFIG_BCMA_POSSIBLE

#define CONFIG_BCMA_BLOCKIO
#define CONFIG_BCMA_HOST_PCI_POSSIBLE
#define CONFIG_BCMA_HOST_PCI

#define CONFIG_MFD_CORE
#define CONFIG_MFD_88PM860X
#define CONFIG_HTC_I2CPLD
#define CONFIG_MFD_TPS6586X
#define CONFIG_MFD_TPS65910
#define CONFIG_MFD_TPS65912
#define CONFIG_MFD_TPS65912_I2C
#define CONFIG_MFD_TPS65912_SPI
#define CONFIG_MFD_STMPE
#define CONFIG_MFD_TC3589X
#define CONFIG_PMIC_DA903X
#define CONFIG_PMIC_ADP5520
#define CONFIG_MFD_MAX8925
#define CONFIG_MFD_MAX8997
#define CONFIG_MFD_MAX8998
#define CONFIG_MFD_WM831X
#define CONFIG_MFD_WM831X_I2C
#define CONFIG_MFD_WM831X_SPI
#define CONFIG_MFD_WM8350
#define CONFIG_MFD_WM8350_I2C
#define CONFIG_MFD_WM8994
#define CONFIG_ABX500_CORE
#define CONFIG_AB3100_CORE
#define CONFIG_AB8500_CORE
#define CONFIG_AB8500_DEBUG
#define CONFIG_AB8500_GPADC
#define CONFIG_MFD_AAT2870_CORE
#define CONFIG_REGULATOR
#define CONFIG_REGULATOR_DEBUG
#define CONFIG_REGULATOR_88PM8607
#define CONFIG_REGULATOR_AB8500

#define CONFIG_DVB_NET

#define CONFIG_MEDIA_ATTACH
#define CONFIG_VIDEO_CAPTURE_DRIVERS
#define CONFIG_VIDEO_HELPER_CHIPS_AUTO










#define CONFIG_VIDEO_BT848_DVB
#define CONFIG_VIDEO_SAA7134_RC
#define CONFIG_V4L_USB_DRIVERS
#define CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV
#define CONFIG_VIDEO_PVRUSB2_SYSFS
#define CONFIG_VIDEO_PVRUSB2_DVB
#define CONFIG_VIDEO_EM28XX_RC
#define CONFIG_VIDEO_CX231XX_RC
#define CONFIG_USB_PWC_INPUT_EVDEV
#define CONFIG_V4L_MEM2MEM_DRIVERS
#define CONFIG_RADIO_ADAPTERS
#define CONFIG_RADIO_SI470X

#define CONFIG_DVB_DYNAMIC_MINORS
#define CONFIG_DVB_CAPTURE_DRIVERS

#define CONFIG_DVB_AV7110_OSD







#define CONFIG_DVB_FIREDTV_INPUT
















#define CONFIG_AGP
#define CONFIG_AGP_AMD
#define CONFIG_AGP_AMD64
#define CONFIG_AGP_INTEL
#define CONFIG_AGP_NVIDIA
#define CONFIG_AGP_VIA
#define CONFIG_VGA_ARB
#define CONFIG_VGA_SWITCHEROO
#define CONFIG_DRM_LOAD_EDID_FIRMWARE
#define CONFIG_DRM_RADEON_KMS
#define CONFIG_DRM_I915_KMS
#define CONFIG_FB
#define CONFIG_FIRMWARE_EDID
#define CONFIG_FB_BOOT_VESA_SUPPORT
#define CONFIG_FB_CFB_FILLRECT
#define CONFIG_FB_CFB_COPYAREA
#define CONFIG_FB_CFB_IMAGEBLIT
#define CONFIG_FB_DEFERRED_IO
#define CONFIG_FB_BACKLIGHT
#define CONFIG_FB_MODE_HELPERS
#define CONFIG_FB_TILEBLITTING

#define CONFIG_FB_PM2_FIFO_DISCONNECT
#define CONFIG_FB_CYBER2000_DDC
#define CONFIG_FB_ASILIANT
#define CONFIG_FB_IMSTT
#define CONFIG_FB_EFI
#define CONFIG_FB_NVIDIA_I2C
#define CONFIG_FB_NVIDIA_BACKLIGHT
#define CONFIG_FB_RIVA_I2C
#define CONFIG_FB_RIVA_BACKLIGHT
#define CONFIG_FB_INTEL_I2C
#define CONFIG_FB_MATROX_MILLENIUM
#define CONFIG_FB_MATROX_MYSTIQUE
#define CONFIG_FB_MATROX_G
#define CONFIG_FB_RADEON_I2C
#define CONFIG_FB_RADEON_BACKLIGHT
#define CONFIG_FB_ATY128_BACKLIGHT
#define CONFIG_FB_ATY_CT
#define CONFIG_FB_ATY_GENERIC_LCD
#define CONFIG_FB_ATY_GX
#define CONFIG_FB_ATY_BACKLIGHT
#define CONFIG_FB_S3_DDC
#define CONFIG_FB_SAVAGE_I2C
#define CONFIG_FB_SAVAGE_ACCEL
#define CONFIG_FB_SIS_300
#define CONFIG_FB_SIS_315
#define CONFIG_FB_VIA_X_COMPATIBILITY
#define CONFIG_FB_3DFX_I2C
#define CONFIG_FB_CARMINE_DRAM_EVAL
#define CONFIG_FB_GEODE
#define CONFIG_FB_TMIO_ACCELL
#define CONFIG_FB_MB862XX_PCI_GDC
#define CONFIG_FB_MB862XX_I2C
#define CONFIG_BACKLIGHT_LCD_SUPPORT
#define CONFIG_BACKLIGHT_CLASS_DEVICE



#define CONFIG_VGA_CONSOLE
#define CONFIG_DUMMY_CONSOLE
#define CONFIG_FRAMEBUFFER_CONSOLE
#define CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY
#define CONFIG_FONT_8x8
#define CONFIG_FONT_8x16
#define CONFIG_SOUND_OSS_CORE
#define CONFIG_SOUND_OSS_CORE_PRECLAIM
#define CONFIG_SND_JACK
#define CONFIG_SND_OSSEMUL
#define CONFIG_SND_SEQ_HRTIMER_DEFAULT
#define CONFIG_SND_DYNAMIC_MINORS
#define CONFIG_SND_SUPPORT_OLD_API
#define CONFIG_SND_VERBOSE_PROCFS
#define CONFIG_SND_VMASTER
#define CONFIG_SND_KCTL_JACK
#define CONFIG_SND_DMA_SGBUF
#define CONFIG_SND_DRIVERS
#define CONFIG_SND_AC97_POWER_SAVE
#define CONFIG_SND_ISA
#define CONFIG_SND_SB16_CSP
#define CONFIG_SND_PCI
#define CONFIG_SND_CS46XX_NEW_DSP
#define CONFIG_SND_ES1968_INPUT
#define CONFIG_SND_ES1968_RADIO
#define CONFIG_SND_FM801_TEA575X_BOOL
#define CONFIG_SND_HDA_HWDEP
#define CONFIG_SND_HDA_RECONFIG
#define CONFIG_SND_HDA_INPUT_BEEP
#define CONFIG_SND_HDA_INPUT_JACK
#define CONFIG_SND_HDA_PATCH_LOADER
#define CONFIG_SND_HDA_CODEC_REALTEK
#define CONFIG_SND_HDA_ENABLE_REALTEK_QUIRKS
#define CONFIG_SND_HDA_CODEC_ANALOG
#define CONFIG_SND_HDA_CODEC_SIGMATEL
#define CONFIG_SND_HDA_CODEC_VIA
#define CONFIG_SND_HDA_CODEC_HDMI
#define CONFIG_SND_HDA_CODEC_CIRRUS
#define CONFIG_SND_HDA_CODEC_CONEXANT
#define CONFIG_SND_HDA_CODEC_CA0110
#define CONFIG_SND_HDA_CODEC_CA0132
#define CONFIG_SND_HDA_CODEC_CMEDIA
#define CONFIG_SND_HDA_CODEC_SI3054
#define CONFIG_SND_HDA_GENERIC
#define CONFIG_SND_HDA_POWER_SAVE
#define CONFIG_SND_MAESTRO3_INPUT
#define CONFIG_SND_SPI
#define CONFIG_SND_USB
#define CONFIG_SND_USB_CAIAQ_INPUT
#define CONFIG_SND_FIREWIRE
#define CONFIG_SND_PCMCIA
#define CONFIG_HID_SUPPORT
#define CONFIG_HIDRAW

#define CONFIG_HID_PID
#define CONFIG_USB_HIDDEV


#define CONFIG_HID_ACRUX_FF
#define CONFIG_DRAGONRISE_FF
#define CONFIG_HOLTEK_FF
#define CONFIG_LOGITECH_FF
#define CONFIG_LOGIRUMBLEPAD2_FF
#define CONFIG_LOGIG940_FF
#define CONFIG_LOGIWHEELS_FF
#define CONFIG_PANTHERLORD_FF
#define CONFIG_HID_PICOLCD_FB
#define CONFIG_HID_PICOLCD_BACKLIGHT
#define CONFIG_HID_PICOLCD_LCD
#define CONFIG_HID_PICOLCD_LEDS
#define CONFIG_GREENASIA_FF
#define CONFIG_SMARTJOYPLUS_FF
#define CONFIG_THRUSTMASTER_FF
#define CONFIG_HID_WACOM_POWER_SUPPLY
#define CONFIG_ZEROPLUS_FF
#define CONFIG_USB_SUPPORT
#define CONFIG_USB_COMMON
#define CONFIG_USB_ARCH_HAS_HCD
#define CONFIG_USB_ARCH_HAS_OHCI
#define CONFIG_USB_ARCH_HAS_EHCI
#define CONFIG_USB_ARCH_HAS_XHCI
#define CONFIG_USB

#define CONFIG_USB_SUSPEND
#define CONFIG_USB_MON

#define CONFIG_USB_XHCI_HCD
#define CONFIG_USB_EHCI_HCD
#define CONFIG_USB_EHCI_ROOT_HUB_TT
#define CONFIG_USB_EHCI_TT_NEWSCHED
#define CONFIG_USB_OHCI_HCD
#define CONFIG_USB_OHCI_LITTLE_ENDIAN
#define CONFIG_USB_UHCI_HCD
#define CONFIG_USB_SL811_HCD_ISO



#define CONFIG_REALTEK_AUTOPM
#define CONFIG_USB_LIBUSUAL


#define CONFIG_USB_EZUSB
#define CONFIG_USB_SERIAL_GENERIC
#define CONFIG_USB_SERIAL_KEYSPAN_MPR
#define CONFIG_USB_SERIAL_KEYSPAN_USA28
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XA
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XB
#define CONFIG_USB_SERIAL_KEYSPAN_USA19
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W
#define CONFIG_USB_SERIAL_KEYSPAN_USA49WLC
#define CONFIG_USB_SERIAL_MOS7715_PARPORT

#define CONFIG_USB_NET2272_DMA
#define CONFIG_USB_GADGET_DUALSPEED
#define CONFIG_USB_GADGET_SUPERSPEED
#define CONFIG_USB_ETH_RNDIS
#define CONFIG_USB_FUNCTIONFS_ETH
#define CONFIG_USB_FUNCTIONFS_RNDIS
#define CONFIG_USB_FUNCTIONFS_GENERIC
#define CONFIG_USB_G_DBGP_SERIAL

#define CONFIG_USB_OTG_UTILS
#define CONFIG_MMC

#define CONFIG_MMC_BLOCK_BOUNCE

#define CONFIG_MMC_RICOH_MMC


#define CONFIG_NEW_LEDS
#define CONFIG_LEDS_CLASS

#define CONFIG_LEDS_PCA9532_GPIO
#define CONFIG_LEDS_TRIGGERS


#define CONFIG_INFINIBAND_USER_MEM
#define CONFIG_INFINIBAND_ADDR_TRANS
#define CONFIG_INFINIBAND_MTHCA_DEBUG
#define CONFIG_INFINIBAND_AMSO1100_DEBUG
#define CONFIG_INFINIBAND_IPOIB_CM
#define CONFIG_INFINIBAND_IPOIB_DEBUG
#define CONFIG_EDAC

#define CONFIG_RTC_LIB
#define CONFIG_RTC_CLASS
#define CONFIG_RTC_HCTOSYS

#define CONFIG_RTC_INTF_SYSFS
#define CONFIG_RTC_INTF_PROC
#define CONFIG_RTC_INTF_DEV

#define CONFIG_RTC_DRV_M41T80_WDT


#define CONFIG_RTC_DRV_CMOS

#define CONFIG_DMADEVICES

#define CONFIG_DMA_ENGINE

#define CONFIG_NET_DMA
#define CONFIG_ASYNC_TX_DMA
#define CONFIG_AUXDISPLAY
#define CONFIG_VIRTIO
#define CONFIG_VIRTIO_RING

#define CONFIG_VIRTIO_PCI

#define CONFIG_XEN_BALLOON
#define CONFIG_XEN_SELFBALLOONING
#define CONFIG_XEN_SCRUB_PAGES
#define CONFIG_XEN_BACKEND
#define CONFIG_XEN_COMPAT_XENFS
#define CONFIG_XEN_SYS_HYPERVISOR
#define CONFIG_XEN_XENBUS_FRONTEND
#define CONFIG_SWIOTLB_XEN
#define CONFIG_XEN_TMEM
#define CONFIG_XEN_ACPI_PROCESSOR
#define CONFIG_STAGING
#define CONFIG_DRM_NOUVEAU_BACKLIGHT
#define CONFIG_DRM_NOUVEAU_DEBUG




#define CONFIG_IIO_BUFFER
#define CONFIG_IIO_TRIGGER

#define CONFIG_LIS3L02DQ_BUF_KFIFO

#define CONFIG_AD799X_RING_BUFFER
#define CONFIG_MAX1363_RING_BUFFER












#define CONFIG_XVMALLOC
#define CONFIG_SBE_PMCC4_NCOMM

#define CONFIG_DRM_PSB_MRST
#define CONFIG_DRM_PSB_MFLD
#define CONFIG_STAGING_MEDIA
#define CONFIG_DT3155_STREAMING
#define CONFIG_LIRC_STAGING
#define CONFIG_LIRC_SERIAL_TRANSMITTER
#define CONFIG_X86_PLATFORM_DEVICES
#define CONFIG_SONYPI_COMPAT
#define CONFIG_THINKPAD_ACPI_ALSA_SUPPORT
#define CONFIG_THINKPAD_ACPI_DEBUGFACILITIES
#define CONFIG_THINKPAD_ACPI_VIDEO
#define CONFIG_THINKPAD_ACPI_HOTKEY_POLL

#define CONFIG_CLKSRC_I8253
#define CONFIG_CLKEVT_I8253
#define CONFIG_I8253_LOCK
#define CONFIG_CLKBLD_I8253
#define CONFIG_IOMMU_API
#define CONFIG_IOMMU_SUPPORT
#define CONFIG_DMAR_TABLE
#define CONFIG_INTEL_IOMMU
#define CONFIG_INTEL_IOMMU_FLOPPY_WA
#define CONFIG_VIRT_DRIVERS

#define CONFIG_PM_DEVFREQ

#define CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND
#define CONFIG_DEVFREQ_GOV_PERFORMANCE
#define CONFIG_DEVFREQ_GOV_POWERSAVE
#define CONFIG_DEVFREQ_GOV_USERSPACE


#define CONFIG_AUFS_BRANCH_MAX_127
#define CONFIG_AUFS_SBILIST
#define CONFIG_AUFS_BR_RAMFS
#define CONFIG_AUFS_BR_FUSE
#define CONFIG_AUFS_POLL
#define CONFIG_AUFS_BR_HFSPLUS
#define CONFIG_AUFS_BDEV_LOOP

#define CONFIG_EDD
#define CONFIG_EDD_OFF
#define CONFIG_FIRMWARE_MEMMAP
#define CONFIG_EFI_VARS
#define CONFIG_DMIID
#define CONFIG_ISCSI_IBFT_FIND

#define CONFIG_EXT2_FS_XATTR
#define CONFIG_EXT2_FS_POSIX_ACL
#define CONFIG_EXT2_FS_SECURITY
#define CONFIG_EXT3_FS
#define CONFIG_EXT3_DEFAULTS_TO_ORDERED
#define CONFIG_EXT3_FS_XATTR
#define CONFIG_EXT3_FS_POSIX_ACL
#define CONFIG_EXT3_FS_SECURITY
#define CONFIG_EXT4_FS
#define CONFIG_EXT4_FS_XATTR
#define CONFIG_EXT4_FS_POSIX_ACL
#define CONFIG_EXT4_FS_SECURITY
#define CONFIG_JBD
#define CONFIG_JBD2
#define CONFIG_FS_MBCACHE
#define CONFIG_REISERFS_FS_XATTR
#define CONFIG_REISERFS_FS_POSIX_ACL
#define CONFIG_REISERFS_FS_SECURITY
#define CONFIG_JFS_POSIX_ACL
#define CONFIG_JFS_SECURITY
#define CONFIG_JFS_STATISTICS
#define CONFIG_XFS_QUOTA
#define CONFIG_XFS_POSIX_ACL
#define CONFIG_XFS_RT
#define CONFIG_GFS2_FS_LOCKING_DLM
#define CONFIG_OCFS2_FS_STATS
#define CONFIG_OCFS2_DEBUG_MASKLOG
#define CONFIG_BTRFS_FS_POSIX_ACL
#define CONFIG_FS_POSIX_ACL
#define CONFIG_EXPORTFS
#define CONFIG_FILE_LOCKING
#define CONFIG_FSNOTIFY
#define CONFIG_DNOTIFY
#define CONFIG_INOTIFY_USER
#define CONFIG_FANOTIFY
#define CONFIG_FANOTIFY_ACCESS_PERMISSIONS
#define CONFIG_QUOTA
#define CONFIG_QUOTA_NETLINK_INTERFACE
#define CONFIG_QUOTACTL
#define CONFIG_FUSE_FS
#define CONFIG_GENERIC_ACL

#define CONFIG_FSCACHE_STATS
#define CONFIG_FSCACHE_HISTOGRAM

#define CONFIG_JOLIET
#define CONFIG_ZISOFS
#define CONFIG_UDF_NLS


#define CONFIG_PROC_FS
#define CONFIG_PROC_KCORE
#define CONFIG_PROC_VMCORE
#define CONFIG_PROC_SYSCTL
#define CONFIG_PROC_PAGE_MONITOR
#define CONFIG_SYSFS
#define CONFIG_TMPFS
#define CONFIG_TMPFS_POSIX_ACL
#define CONFIG_TMPFS_XATTR
#define CONFIG_HUGETLBFS
#define CONFIG_HUGETLB_PAGE
#define CONFIG_MISC_FILESYSTEMS
#define CONFIG_ECRYPT_FS
#define CONFIG_JFFS2_FS_WRITEBUFFER
#define CONFIG_JFFS2_COMPRESSION_OPTIONS
#define CONFIG_JFFS2_ZLIB
#define CONFIG_JFFS2_LZO
#define CONFIG_JFFS2_RTIME
#define CONFIG_JFFS2_CMODE_FAVOURLZO
#define CONFIG_UBIFS_FS_XATTR
#define CONFIG_UBIFS_FS_LZO
#define CONFIG_UBIFS_FS_ZLIB
#define CONFIG_SQUASHFS_XATTR
#define CONFIG_SQUASHFS_ZLIB
#define CONFIG_SQUASHFS_LZO
#define CONFIG_SQUASHFS_XZ
#define CONFIG_ROMFS_BACKED_BY_BLOCK
#define CONFIG_ROMFS_ON_BLOCK
#define CONFIG_PSTORE
#define CONFIG_NETWORK_FILESYSTEMS
#define CONFIG_NFS_V3
#define CONFIG_NFS_V3_ACL
#define CONFIG_NFS_V4
#define CONFIG_NFS_FSCACHE
#define CONFIG_NFS_USE_KERNEL_DNS
#define CONFIG_NFSD_V2_ACL
#define CONFIG_NFSD_V3
#define CONFIG_NFSD_V3_ACL
#define CONFIG_NFSD_V4
#define CONFIG_LOCKD_V4
#define CONFIG_NFS_COMMON
#define CONFIG_CIFS_WEAK_PW_HASH
#define CONFIG_CIFS_UPCALL
#define CONFIG_CIFS_XATTR
#define CONFIG_CIFS_POSIX
#define CONFIG_CIFS_DFS_UPCALL
#define CONFIG_NCPFS_PACKET_SIGNING
#define CONFIG_NCPFS_IOCTL_LOCKING
#define CONFIG_NCPFS_STRONG
#define CONFIG_NCPFS_NFS_NS
#define CONFIG_NCPFS_OS2_NS
#define CONFIG_NCPFS_NLS
#define CONFIG_NCPFS_EXTRAS
#define CONFIG_9P_FS_POSIX_ACL

#define CONFIG_PARTITION_ADVANCED
#define CONFIG_ACORN_PARTITION
#define CONFIG_ACORN_PARTITION_ICS
#define CONFIG_ACORN_PARTITION_RISCIX
#define CONFIG_OSF_PARTITION
#define CONFIG_AMIGA_PARTITION
#define CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION
#define CONFIG_BSD_DISKLABEL
#define CONFIG_MINIX_SUBPARTITION
#define CONFIG_SOLARIS_X86_PARTITION
#define CONFIG_UNIXWARE_DISKLABEL
#define CONFIG_LDM_PARTITION
#define CONFIG_SGI_PARTITION
#define CONFIG_ULTRIX_PARTITION
#define CONFIG_SUN_PARTITION
#define CONFIG_KARMA_PARTITION
#define CONFIG_EFI_PARTITION
#define CONFIG_SYSV68_PARTITION
#define CONFIG_NLS

#define CONFIG_TRACE_IRQFLAGS_SUPPORT
#define CONFIG_PRINTK_TIME
#define CONFIG_MAGIC_SYSRQ
#define CONFIG_UNUSED_SYMBOLS
#define CONFIG_DEBUG_FS
#define CONFIG_DEBUG_KERNEL
#define CONFIG_LOCKUP_DETECTOR
#define CONFIG_HARDLOCKUP_DETECTOR
#define CONFIG_DETECT_HUNG_TASK
#define CONFIG_SCHED_DEBUG
#define CONFIG_SCHEDSTATS
#define CONFIG_TIMER_STATS
#define CONFIG_STACKTRACE
#define CONFIG_DEBUG_BUGVERBOSE
#define CONFIG_DEBUG_INFO
#define CONFIG_DEBUG_MEMORY_INIT
#define CONFIG_ARCH_WANT_FRAME_POINTERS
#define CONFIG_FRAME_POINTER
#define CONFIG_BOOT_PRINTK_DELAY
#define CONFIG_LATENCYTOP
#define CONFIG_SYSCTL_SYSCALL_CHECK
#define CONFIG_USER_STACKTRACE_SUPPORT
#define CONFIG_NOP_TRACER
#define CONFIG_HAVE_FTRACE_NMI_ENTER
#define CONFIG_HAVE_FUNCTION_TRACER
#define CONFIG_HAVE_FUNCTION_GRAPH_TRACER
#define CONFIG_HAVE_FUNCTION_GRAPH_FP_TEST
#define CONFIG_HAVE_FUNCTION_TRACE_MCOUNT_TEST
#define CONFIG_HAVE_DYNAMIC_FTRACE
#define CONFIG_HAVE_FTRACE_MCOUNT_RECORD
#define CONFIG_HAVE_SYSCALL_TRACEPOINTS
#define CONFIG_HAVE_C_RECORDMCOUNT
#define CONFIG_TRACER_MAX_TRACE
#define CONFIG_RING_BUFFER
#define CONFIG_FTRACE_NMI_ENTER
#define CONFIG_EVENT_TRACING
#define CONFIG_EVENT_POWER_TRACING_DEPRECATED
#define CONFIG_CONTEXT_SWITCH_TRACER
#define CONFIG_RING_BUFFER_ALLOW_SWAP
#define CONFIG_TRACING
#define CONFIG_GENERIC_TRACER
#define CONFIG_TRACING_SUPPORT
#define CONFIG_FTRACE
#define CONFIG_FUNCTION_TRACER
#define CONFIG_FUNCTION_GRAPH_TRACER
#define CONFIG_SCHED_TRACER
#define CONFIG_FTRACE_SYSCALLS
#define CONFIG_BRANCH_PROFILE_NONE
#define CONFIG_STACK_TRACER
#define CONFIG_BLK_DEV_IO_TRACE
#define CONFIG_KPROBE_EVENT
#define CONFIG_DYNAMIC_FTRACE
#define CONFIG_FUNCTION_PROFILER
#define CONFIG_FTRACE_MCOUNT_RECORD
#define CONFIG_MMIOTRACE
#define CONFIG_HAVE_ARCH_KGDB
#define CONFIG_KGDB
#define CONFIG_KGDB_SERIAL_CONSOLE
#define CONFIG_KGDB_LOW_LEVEL_TRAP
#define CONFIG_KGDB_KDB
#define CONFIG_KDB_KEYBOARD
#define CONFIG_HAVE_ARCH_KMEMCHECK
#define CONFIG_STRICT_DEVMEM
#define CONFIG_EARLY_PRINTK
#define CONFIG_DEBUG_RODATA
#define CONFIG_DEBUG_SET_MODULE_RONX
#define CONFIG_DOUBLEFAULT
#define CONFIG_HAVE_MMIOTRACE_SUPPORT
#define CONFIG_IO_DELAY_0XED
#define CONFIG_OPTIMIZE_INLINING

#define CONFIG_KEYS
#define CONFIG_TRUSTED_KEYS
#define CONFIG_ENCRYPTED_KEYS
#define CONFIG_SECURITY
#define CONFIG_SECURITYFS
#define CONFIG_SECURITY_NETWORK
#define CONFIG_SECURITY_PATH
#define CONFIG_SECURITY_SELINUX
#define CONFIG_SECURITY_SELINUX_BOOTPARAM
#define CONFIG_SECURITY_SELINUX_DISABLE
#define CONFIG_SECURITY_SELINUX_DEVELOP
#define CONFIG_SECURITY_SELINUX_AVC_STATS
#define CONFIG_SECURITY_SMACK
#define CONFIG_SECURITY_TOMOYO
#define CONFIG_SECURITY_APPARMOR
#define CONFIG_SECURITY_YAMA
#define CONFIG_INTEGRITY
#define CONFIG_EVM
#define CONFIG_DEFAULT_SECURITY_APPARMOR
#define CONFIG_ASYNC_TX_DISABLE_PQ_VAL_DMA
#define CONFIG_ASYNC_TX_DISABLE_XOR_VAL_DMA
#define CONFIG_CRYPTO

#define CONFIG_CRYPTO_ALGAPI
#define CONFIG_CRYPTO_ALGAPI2
#define CONFIG_CRYPTO_AEAD2
#define CONFIG_CRYPTO_BLKCIPHER
#define CONFIG_CRYPTO_BLKCIPHER2
#define CONFIG_CRYPTO_HASH
#define CONFIG_CRYPTO_HASH2
#define CONFIG_CRYPTO_RNG
#define CONFIG_CRYPTO_RNG2
#define CONFIG_CRYPTO_PCOMP2
#define CONFIG_CRYPTO_MANAGER
#define CONFIG_CRYPTO_MANAGER2
#define CONFIG_CRYPTO_MANAGER_DISABLE_TESTS
#define CONFIG_CRYPTO_WORKQUEUE


#define CONFIG_CRYPTO_CBC
#define CONFIG_CRYPTO_ECB

#define CONFIG_CRYPTO_HMAC

#define CONFIG_CRYPTO_CRC32C
#define CONFIG_CRYPTO_CRC32C_INTEL
#define CONFIG_CRYPTO_MD5
#define CONFIG_CRYPTO_SHA1
#define CONFIG_CRYPTO_SHA256

#define CONFIG_CRYPTO_AES


#define CONFIG_CRYPTO_HW
#define CONFIG_CRYPTO_DEV_PADLOCK
#define CONFIG_HAVE_KVM
#define CONFIG_HAVE_KVM_IRQCHIP
#define CONFIG_HAVE_KVM_EVENTFD
#define CONFIG_KVM_APIC_ARCHITECTURE
#define CONFIG_KVM_MMIO
#define CONFIG_KVM_ASYNC_PF
#define CONFIG_VIRTUALIZATION
#define CONFIG_BINARY_PRINTF

#define CONFIG_BITREVERSE
#define CONFIG_GENERIC_FIND_FIRST_BIT
#define CONFIG_CRC16
#define CONFIG_CRC_T10DIF
#define CONFIG_CRC32
#define CONFIG_AUDIT_GENERIC
#define CONFIG_ZLIB_INFLATE
#define CONFIG_LZO_COMPRESS
#define CONFIG_LZO_DECOMPRESS
#define CONFIG_XZ_DEC
#define CONFIG_XZ_DEC_X86
#define CONFIG_XZ_DEC_POWERPC
#define CONFIG_XZ_DEC_IA64
#define CONFIG_XZ_DEC_ARM
#define CONFIG_XZ_DEC_ARMTHUMB
#define CONFIG_XZ_DEC_SPARC
#define CONFIG_XZ_DEC_BCJ
#define CONFIG_DECOMPRESS_GZIP
#define CONFIG_DECOMPRESS_BZIP2
#define CONFIG_DECOMPRESS_LZMA
#define CONFIG_DECOMPRESS_XZ
#define CONFIG_DECOMPRESS_LZO
#define CONFIG_GENERIC_ALLOCATOR
#define CONFIG_REED_SOLOMON_DEC16
#define CONFIG_TEXTSEARCH
#define CONFIG_HAS_IOMEM
#define CONFIG_HAS_IOPORT
#define CONFIG_HAS_DMA
#define CONFIG_CHECK_SIGNATURE
#define CONFIG_CPU_RMAP
#define CONFIG_NLATTR
#define CONFIG_AVERAGE

#endif /* _LINUX_CONFIGS_H_ */
