.\" =========================================================================
.\" isr - Client user interface for the Internet Suspend/Resume (R) system
.\" 
.\" Copyright (C) 2004-2010 Carnegie Mellon University
.\" 
.\" This software is distributed under the terms of the Eclipse Public
.\" License, Version 1.0 which can be found in the file named LICENSE.Eclipse.
.\" ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
.\" RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
.\" ==========================================================================
.\"
.TH ISR 1 "" "OpenISR 0.10.1" "User Commands"

.SH NAME
isr \- Internet Suspend/Resume client program

.SH SYNOPSIS
.B isr 
.I command
.RI [ parcel ]
.RB [ \-bcdDefFlpqvY ]
.RB [ \-s
.IR server ]
.RB [ \-u
.IR userid ]
.RB [ \-r
.IR version ]
.RB [ \-m
.IR vmm ]
.RB [ \-o
.IR optstring ]
.RB [ \-C
.IR compression ]
.RB [ \-L
.IR count ]

.I Commands: 
.B auth, checkin (ci), checkout (co), checkhoard, checkp, clean, deauth, dirtometer, discard, help, hoard, ls, lshoard, passwd, poweroff, resume, rmhoard, stat, sync, uuid, version

.SH DESCRIPTION
An Internet Suspend/Resume\*R (ISR) system is a collection of
virtual machine
.I parcels
on a 
.IR server ,
together with a set of 
.IR "client hosts" ,
each loaded with the 
.B isr
client program and a 
.IR "virtual machine monitor" .
A parcel is a set of data that represents all of the state of some
virtual machine in execution, and includes a
.IR keyring ", a " "memory image" ", and a " "virtual disk" .
The server maintains checkpointed versions of each parcel.

Each ISR user has a unique
.I ISR userid
and a corresponding 
.I ISR password
on the server.
Distinct ISR userids own disjoint sets of parcels. Parcels are not
shared across ISR userids. At any point in time, a parcel can be
checked out on at most one client host. A simple locking mechanism
enforces this policy.


The 
.B isr
client program provides commands to 
.I checkout 
(download) parcels from the server to the client host, 
run parcels on the client host, 
.I checkin 
(upload) parcels from the client
host back to the server, query the status of parcels,
authenticate to the ISR system, and change the ISR password.
Downloading and running a parcel is known as 
.I resuming
the parcel. 
Locally suspending the virtual machine monitor 
and then uploading the parcel back
to the server is known as
.I suspending
the parcel.

The 
.B isr
client program also provides a command to
.B hoard
parcel state into a persistent 
.I hoard cache
on the client host.
A fully-hoarded parcel is one where the hoard cache contains the parcel's
entire virtual disk state; thus the parcel, once checked out, can be
resumed
.I disconnected
(without a network connection). Use the 
.B lshoard
command to view the state of the hoard cache on your client, and the
.B stat
command to see how much of a particular parcel is currently hoarded.

On a particular client host, the
.I default server
is given by the 
.I server 
variable in 
.IR /usr/local/share/openisr/config ,
which may be overridden in the system config file in
.I /usr/local/etc/openisr/openisr.conf
or the user config file in
.IR ~/.openisrrc .
If necessary, however, the server can be specified on
the command line using the
.B -s 
command line option.

By default, the 
.I current ISR userid
is the current Unix login name. This can be overridden by 
setting the
.I userid
config option in 
.I /usr/local/etc/openisr/openisr.conf
or
.IR ~/.openisrrc ,
which in turn can be overridden by specifying the  
.B -u
option on the command line.

You can safely attempt to interrupt any
.B isr
command at any time by typing control-c (SIGINT).  Regions of commands
that should not be interrupted will ignore these SIGINT signals.

.SH COMMANDS 

.TP
.BI "isr auth"
Authenticate to the ISR server. You will be prompted for your ISR
password.  Run this command once, at the beginning of each X session
to avoid having to keep typing your ISR password.


.TP
.BI "isr checkin(ci) " parcel " [-b " "KBytes/s" "] [-C " "compression" "]"
Checkin a 
.I parcel 
to the server. This command creates a new checkpointed version
of the parcel on the server, and then releases a lock on the
parcel so that it can be resumed by other client hosts.
The 
.B -b
option limits the upload bandwidth to 
.I KBytes/s.
The
.B -C
option specifies the algorithm used to compress the memory image for
upload; see
.B OPTIONS
below for supported values of
.IR compression .

The
.B checkin
command is 
.IR idempotent , 
meaning that it can be safely interrupted with ctrl-c and rerun until
it successfully completes.

.TP
.BI "isr checkout(co) " "parcel" " [-c] [-d] [-r " "oldversion" "]"
Download  a 
.I parcel 
from the server without running it.  This command acquires a lock on the
parcel and downloads the minimum amount of virtual machine state needed to
run the parcel on the client host.

By default, the 
.B checkout
command downloads the most recent parcel
version. However, you can rollback to previous parcel versions using
the
.BI -r 
.I oldversion
option. Let 
.I lastversion
be the most recent parcel version on the server. Then
.B -r 
.I oldversion
causes the server to first create a new version
.I lastversion+1
that is an identical copy  of version
.IR oldversion .
This new version, which is now the most recent version, 
is then downloaded as before. 

The
.B -d
option will additionally
.B hoard
the parcel after downloading it, ensuring that you will be able to
.B resume
the parcel when disconnected from the network.  The
.B -c
option, when used in conjunction with the
.B -d
option, performs lengthy consistency checks on the hoard cache after
hoarding has completed.

The 
.B checkout
command is useful for preparing a parcel to run
.IR disconnected ,
but it is normally subsumed by the 
.B resume 
command when you are running
.IR connected .
Even in connected mode, it can be useful in some situations.
For example, you might want to use the 
.B stat
command (which requires the parcel to be checked out) 
before you actually run the parcel.


.TP
.BI "isr checkp " "parcel" " [-e] [-r " "version" "] [-c] [-Y]"
This is a debugging command that checks a 
.I parcel 
for consistency.  By default, this command performs fast sanity checks
on the local cache of a checked-out
.IR parcel .
The
.B -e
option causes the command to check a particular version of the
.I parcel
on the server instead.  By default,
.B -e
checks the most recent
.IR version ,
but the
.B -r
option can be used to specify a different
.I version
instead.  The
.B -c
option performs an additional (and time-consuming) content consistency
check on the server
.I version
(if 
.B -e
is specified) or on the local cache (otherwise).

The
.B -Y
option is similar to
.BR -c ,
but will additionally revert any inconsistent disk chunks to their state
at the most recent checkout or sync operation.  This operation will only
revert chunks whose data does not match the stored hash, as might result
from an OpenISR or client host crash; it will not correct more exotic
metadata errors.  The disk image resulting from this operation will be
inconsistent from the point of view of the guest operating system, but it
may allow the parcel to be resumed long enough to retrieve data from the
damaged disk image.  (For example, if a damaged chunk contains filesystem
metadata, it might be preferable for the guest operating system to read
obsolete data than to receive I/O errors when trying to read the chunk.)
If any chunks are reverted using this option, the local cache of the parcel
will be marked as
.I damaged
and subsequent checkin attempts will be disallowed.  The
.B -Y
option cannot be used with
.BR -e .

.TP
.B "isr checkhoard [-c] [-p]"
This is a maintenance command that checks the hoard cache for consistency
and repairs any problems it finds.  By default, this command performs
fast checks on the hoard cache indexes.  The
.B -c
option causes it to perform an additional (and time-consuming) content
consistency check.  The
.B -p
option defragments the hoard cache and resizes it to the smallest possible
size.

.TP
.BI "isr clean " "parcel" " [-f]"
Remove  
.I parcel 
from the client host and release its server lock.  This command can be used
as a faster alternative to 
.B checkin
when you don't need to save any of the changes you have made to
.I parcel
since the last
.B checkout
or
.BR sync .

The
.B -f
option forcibly releases the server lock, even if it is held by a different
client host.  That client host will be unable to checkin the parcel.  This
option can be useful if you've forgotten to checkin the parcel and want to
use it from another client host.

.TP
.BI "isr deauth" 
Remove the authentication credentials that were established by the
.B auth
command.

.TP
.BI "isr dirtometer " parcel
Launch the dirtometer for
.IR parcel ,
which must already be resumed.  The dirtometer is a visualization tool which
shows virtual disk accesses by the guest OS and the resulting parcel state.

To automatically launch the dirtometer when a parcel is resumed, pass
.B -D
to
.B isr resume
or set the
.I dirtometer
option in ~/.openisrrc.

.TP
.BI "isr discard " "parcel"
Discard all local client changes to 
.I parcel 
since the last 
.B checkout
or 
.BR sync .
This command is useful for "micro-rollbacks" that allow 
you to recover from mistakes during the current session. For example, 
if you inadvertently type "rm -rf /bin" as root in the guest, the
.B
discard 
command will allow you to rollback to the parcel that existed at the time
of the most recent 
.B
checkout 
or
.B
sync
command.

.TP
.BI "isr help"
Display a brief usage summary.

.TP
.BI "isr hoard " "parcel"
Fetch the parcel's entire virtual disk into the hoard cache
on the client. This command
fetches only the blocks that are missing on the client. You can kill
it with
.B ctrl-c
and rerun it as many times as you wish without any ill effects.

You can hoard a parcel anytime and anywhere, even if other
.B isr 
commands are currently running, and even if the parcel is not
currently checked out on the client host.

.TP
.BI "isr ls [" parcel "] [-l|-L " "n" "]"
List information about your parcels. By default, this command displays
the status of all of the user's parcels that are managed by the
default server. The display identifies the server, and then for
each parcel, prints a single line with the name, the current lock status
.IR "" ( acquired " or " released ),
the user and client host that last changed the lock status, and the
time of that change.  

If a specific parcel is named on the command line, only information
about that parcel will be shown.  The 
.B -L
option requests a long listing format, printing 
additional information about the 
.I n
most recent parcel versions.
The 
.B -l 
option is similar, printing information for some
small default number of the most recent versions.

.TP
.B isr lshoard [-l]
List information about the parcels currently in the hoard cache.  The
.B -l
option causes additional information to be displayed, including parcel
UUIDs for passing to the
.B rmhoard
command.

.TP
.BI "isr passwd" 
Change your ISR password.
This command does 
.B NOT 
change the password of the Unix login
account on your client host. (Use the local
.B passwd
command for that.)  

.TP
.BI "isr poweroff " "parcel" " [-m " "vmm" "] [-o " "optstring" "]"
Forcibly power off a suspended
.I parcel
by deleting its memory image.  When
.I parcel
is next resumed, it will perform a cold boot.  This command can be used to
reboot a misbehaving parcel or to recover if its memory image is damaged.  The
.B -o
option will pass the
.I optstring
configuration option to the VMM.  The
.B -m
option will delete the memory image for the specified
.IR vmm ,
rather than for the parcel's default VMM.

.TP
.BI "isr resume " "parcel" " [-C " "compression" "] [-r " "oldversion" "] [-m " "vmm" "] [-o " "optstring" "] [-d] [-D] [-F]"
Checkout a 
.I parcel
(if necessary) and then run it. Any additional state that the parcel
needs while it is running, beyond that downloaded by the checkout operation,
will be demand-paged from the server.

By default, the 
.B resume 
command requires a network connection. 
However, if the parcel is fully hoarded then you can use the 
.B -d
option to resume
.IR disconnected .
If the parcel is not fully hoarded, the
.B -d
option will remind you to run
.B isr checkout -d
to check out and hoard the parcel.

The
.B -r
option allows you to rollback to previous parcel versions, 
as described in the documentation for the 
.B checkout
command.  The 
.B -F 
option causes the parcel to be resumed in a window rather than in
full-screen mode, which can be useful for configuring the virtual
machine monitor or for running multiple parcels at once.  This option
may be unavailable if the VMM does not support it.  The
.B -D
option launches the dirtometer, which provides a visual representation of
parcel disk accesses and the resulting parcel state.  The
.B -C
option specifies the algorithm used to compress newly-written disk chunks;
see
.B OPTIONS
below for supported values of
.IR compression .

The
.B -m
option allows you to resume using a virtual machine monitor other than the
default VMM for this parcel.  This will fail if the parcel includes a memory
image written by an incompatible VMM, if the VMM is not properly installed
on the client host, or if the guest OS does not support the target VMM.  The
.B -o
option will pass the
.I optstring
configuration option to the VMM.

.TP
.BI "isr rmhoard " parcel
Remove hoarded state for
.I parcel
from the client.  If
.I parcel
is currently checked out, it can be specified by name; otherwise,
it must be specified by its UUID.  The
.I parcel
UUID can be obtained with the
.B lshoard -l
command.

.TP
.BI "isr stat " parcel
Display information about the local state of a 
.IR parcel ,
such as the amount of state demand-paged from the server,
the amount of dirty state, and the amount of state that
is hoarded in the persistent hoard cache.  The
.I parcel
must be checked out in order to use the
.B stat
command.

.TP
.BI "isr sync " parcel " [-b " "KBytes/s" "] [-C " "compression" "]"
Save a new checkpointed version of 
.I parcel 
on the server, without releasing the lock or 
.BR discard ing 
any of the current local state. You can
.B sync
as often as you like between 
.B resume
commands. 
The 
.B -b
option limits the upload bandwidth to 
.IR KBytes/s .
The
.B -C
option specifies the algorithm used to compress the memory image for
upload; see
.B OPTIONS
below for supported values of
.IR compression .

The
.B sync
command is 
.IR idempotent , 
meaning that it can be safely interrupted with ctrl-c and rerun until
it successfully completes.

.TP
.BI "isr uuid " parcel
Display the universally unique identifier (UUID) for the specified
.IR parcel ,
which must be checked out.

.TP
.BI "isr version"
Display the version of the ISR client.

.SH OPTIONS
Each option has equivalent short and long forms.

.TP
.BI -b/--bwlimit " KBytes/s"
Limit upload bandwidth 
during
.B checkin
and 
.B sync
to 
.IR KBytes/s .

.TP
.B -c/--checkstate
Perform an additional content consistency check during the 
.BR checkp ", " checkhoard ", and " checkout
commands.

.TP
.BI -C/--compression " compression"
Override the configured compression profile, which determines how hard
the ISR client should try to compress newly-generated disk chunks (at
runtime) and memory images (at checkin/sync).  The default is obtained
from the
.B compression
option in the configuration files (see
.B FILES
below).  Recognized values of
.I compression
are:

.RS
.TP
.B disabled
Do not compress at all.  This is intended for debugging purposes only;
.B mild
will almost always perform better.
.TP
.B mild
Use a very fast algorithm which compresses poorly.  Choose this option
to improve runtime performance if you have a LAN-speed connection to
the server.  This is the default if no compression profile has been
configured.
.TP
.B moderate
Use an algorithm which is reasonably good and reasonably fast.  Choose
this option for intermediate-bandwidth connections such as fast broadband.
.TP
.B painful
Attempt to compress as much as possible, and spend a lot of time doing it.
This option is appropriate for very slow links.
.RE

.IP
Older parcels may not be configured to support all of these compression
profiles; in this case, the closest match will be used.

.TP
.B -d/--disconnected
.B Resume
disconnected (after hoarding), or ensure that the parcel can later
be resumed disconnected.

.TP
.B -D/--dirtometer
Upon
.BR resume ,
launch the dirtometer, a visualization tool which shows virtual disk accesses
by the guest OS and the resulting parcel state.

.TP
.B -e/--remote
For
.BR checkp ,
check the parcel on the server rather than on the client.

.TP
.B -f/--force
Cause
.B clean
to release the parcel lock on the server even if the lock is held by another
client host.  This will cause that client host to be unable to checkin the
parcel.

.TP
.B -F/--no-fullscreen
When the parcel is resumed, display it in a window rather than in
full-screen mode.

.TP
.B -l/--long
Use long listing format for the 
.B ls
command, printing information about some small default 
number of the most recent parcel versions.  For the
.B lshoard
command, show additional information about the parcels being examined.

.TP
.BI -L/--longvers " n"
Use long listing format for the 
.B ls
command, printing information about the 
.I n
most recent parcel versions.

.TP
.BI -m/--vmm " vmm"
For
.BR resume " or " poweroff ,
use a virtual machine monitor other than the parcel's default.

.TP
.BI -o/--vmmopt " optstring"
For
.BR resume " or " poweroff ,
pass the specified
.I optstring
to the virtual machine monitor.
.I optstring
can contain multiple comma-delimited options.
.B -o
can also be specified more than once.

.TP
.B -p/--compact
During
.BR checkhoard ,
defragment the hoard cache and truncate it to the minimum possible size.

.TP
.B -q/--quiet
Run silently (except if things go wrong).

.TP
.BI -r/--rollback " version"
Optional parcel version number for the 
.BR checkout , " resume" ", and " checkp
commands. For 
.BR checkout " and " resume
it determines the parcel
.I version 
to rollback to. For
.B checkp
it determines the parcel
.I version
to check for consistency if
.B -e
is specified.

.TP
.BI -s/--server " name"
Use the server 
.IR name ,
overriding the default.
.I name
can be a fully qualified domain name or an IP address.

.TP
.BI -u/--user " userid"
By default, the current ISR userid is the current Unix login name
or the value of the
.I userid
variable from the configuration files.  This
option overrides both of these and sets the current ISR userid to
.IR userid .

.TP
.B -v/--verbose
Increment the verbosity level. 

.TP
.B -Y/--splice
For
.B checkp
on a local parcel, revert damaged chunks to their state at the most recent
checkout or sync.  Disallow checkin if any chunks are reverted.

.SH EXAMPLES

Here is how you might use
.B isr
during a typical day: 

After arriving at work, you login to your ISR client host. Next, you will
need to authenticate to the ISR server,

.RS
\fC$ isr auth\fP
.RE

which prompts you for your ISR password.  You are now authenticated
and will not need to type this password again until you either explicitly
.B deauth
or terminate your X session.

After listing your available parcels,

.RS
\fC$ isr ls\fP
.RE

you decide to resume the Windows parcel called 
.I winxp
in connected mode:

.RS
\fC$ isr resume winxp\fP
.RE

This downloads parcel
.I winxp
(if necessary)
and executes it inside the virtual machine monitor (VMM).

After running the parcel all morning, you realize you need to head out
to a lunch meeting in a conference room with poor wireless
connectivity. So you suspend the current running parcel, which causes
the VMM to return control to the Linux shell.  After making sure that
it is safe to run disconnected (i.e., your parcel state is hoarded), 

.RS
\fC$ isr co winxp -d\fP
.RE

you unplug the network cable, carry your laptop to the noon meeting, 
and then run you parcel disconnected during the meeting:

.RS
\fC$ isr resume winxp -d\fP
.RE

After the meeting, you head back to the office, plug your network
cable back in, and create a checkpointed version of your current
parcel state on the server:

.RS
\fC$ isr sync winxp\fP
.RE

After running connected for the rest of the day, it's time to head
home. So you terminate the ISR session by checking in your parcel:

.RS
\fC$ isr ci winxp\fP
.RE

Once home, you login to your home ISR client, authenticate to the ISR
server, and then checkout the parcel that you were working on at work:

.RS
\fC$ isr resume winxp\fP
.RE

.SH FILES
.TP
.I /usr/local/share/openisr/config
Configuration file that specifies defaults for ISR configuration options.
This file should not be modified; changes should be made in the system-wide
or user-specific config files instead.

.TP
.I /usr/local/etc/openisr/openisr.conf
Configuration file that specifies system-wide settings.  Options in this
file override those in
.IR /usr/local/share/openisr/config .

.TP
.I ~/.openisrrc
Configuration file that specifies user-specific settings.  Options in this
file override those in
.IR /usr/local/share/openisr/config " and " /usr/local/etc/openisr/openisr.conf .

.SH ACKNOWLEDGMENTS
ISR was developed by Michael Kozuch and Casey Helfrich from Intel
Research Pittsburgh; David O'Hallaron, Mahadev (Satya) Satyanarayanan,
Matt Toups, and Benjamin Gilbert from Carnegie Mellon; and Partho Nath
from Penn State.  Internet Suspend/Resume and OpenISR are registered
trademarks of Carnegie Mellon University.

.\" end of file
