[Time] Decompression -  0:00:36.806965
[Time] Recover(xdelta) image -  0:00:13.352396
kvm -hda /home/krha/Cloudlet/image/SPEECH_BaseVM/recover.qcow2 -m 2048 -monitor telnet:localhost:9862,server,nowait -enable-kvm -net nic -net user -serial none -parallel none -usb -usbdevice tablet -redir tcp:9876::9876 -redir tcp:2222::22 -redir tcp:19092::9092 -redir tcp:6789::6789 -vnc unix:/home/krha/Cloudlet/image/SPEECH_BaseVM/kvm.vnc -incoming "exec:cat /home/krha/Cloudlet/image/SPEECH_BaseVM/recover.mem"
Socket connection time :  0:00:03.617967
info status time:  0:00:00.042851
[Time] Run Snapshot -  0:00:03.822593
