[Time] Decompression -  0:00:20.589614
[Time] Recover(xdelta) image -  0:00:25.945402
kvm -hda /home/krha/Cloudlet/image/MOPED_BaseVM_Disk/recover.qcow2 -m 2048 -monitor telnet:localhost:9862,server,nowait -enable-kvm -net nic -net user -serial none -parallel none -usb -usbdevice tablet -redir tcp:9876::9876 -redir tcp:2222::22 -redir tcp:19092::9092 -redir tcp:6789::6789 -vnc unix:/home/krha/Cloudlet/image/MOPED_BaseVM_Disk/kvm.vnc -incoming "exec:cat /home/krha/Cloudlet/image/MOPED_BaseVM_Disk/recover.mem"
Socket connection time :  0:00:04.437416
connection request
request ret :  2011-12-13 17:55:23.712624
request ret :  2011-12-13 17:55:23.713064
info status time:  0:00:00.040687
[Time] Run Snapshot -  0:00:04.836526
