#!/usr/bin/python
#
# none - OpenISR (R) VMM driver that just waits for SIGINT
#
# Copyright (C) 2008-2009 Carnegie Mellon University
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.  A copy of the GNU General Public License
# should have been distributed along with this program in the file
# LICENSE.GPL.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

import signal
import sys
sys.path.insert(1, '/usr/local/share/openisr')
import vmm
from vmm import *

def info():
	vmm.VMNAME = 'dummy VMM'
	if 'allow_root' in vmm.OPTIONS:
		vmm.USES_ROOT = 'yes'

def run():
	def handle_signal(sig, frame):
		pass

	signal.signal(signal.SIGINT, handle_signal)
	signal.signal(signal.SIGTERM, handle_signal)
	print >>sys.stderr, 'Waiting for interrupt...'
	signal.pause()

def poweroff():
	pass

main()
